'use client'

import { createRoom } from './_actions/createRoom'
import { useMutation } from '@tanstack/react-query'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { LabelTag } from '@/components/ui/labelTag'
import { DisplayHeading, Accent } from '@/components/ui/displayHeading'
import { ArrowButton } from '@/components/ui/arrowButton'

export const CreateRoomSection = () => {
    const router = useRouter()
    const [roomName, setRoomName] = useState<string>('')
    const [maxViewers, setMaxViewers] = useState<number>(10)

    const createRoomMutation = useMutation({
        mutationFn: () => createRoom({ roomName, maxViewers }),
        onSuccess: () => {
            setRoomName('')
            setMaxViewers(10)
        },
    })

    return (
        <div className="min-h-[calc(100dvh-58px)] flex items-center justify-center px-8 py-9">
            <div className="max-w-[560px] w-full">
                <LabelTag className="block mb-2">— New room</LabelTag>
                <DisplayHeading className="text-[clamp(38px,3.9vw,56px)] mb-2">
                    Open a <Accent>private</Accent> stream.
                </DisplayHeading>
                <p className="text-muted-hi text-sm mb-8">
                    A six-digit code is generated when you create the room. Share it however you like.
                </p>

                <div>
                    <label className="block border-t border-b border-border py-4">
                        <LabelTag className="block mb-1.5">Room name</LabelTag>
                        <input
                            type="text"
                            placeholder="Saturday movie night"
                            value={roomName}
                            onChange={(e) => setRoomName(e.target.value)}
                            className="w-full bg-transparent border-none outline-none text-cream font-sans text-base placeholder:text-muted-dim mt-1"
                        />
                    </label>
                    <label className="block border-b border-border py-4">
                        <div className="flex justify-between">
                            <LabelTag>Maximum viewers</LabelTag>
                            <LabelTag className="text-muted-dim">1–500</LabelTag>
                        </div>
                        <input
                            type="number"
                            placeholder="25"
                            value={maxViewers}
                            onChange={(e) => setMaxViewers(Number(e.target.value))}
                            min={1}
                            max={500}
                            className="w-full bg-transparent border-none outline-none text-cream font-mono text-base placeholder:text-muted-dim mt-1.5"
                        />
                    </label>
                    {/* TODO: stream key — to be generated by server action and displayed here */}
                </div>

                <div className="flex gap-3 mt-7">
                    <ArrowButton
                        onClick={() => createRoomMutation.mutate()}
                        disabled={!roomName}
                        className="flex-1"
                    >
                        Open the room
                    </ArrowButton>
                    <button
                        onClick={() => router.push('?section=rooms')}
                        className="bg-transparent text-cream border border-border rounded-sm px-5 py-4 text-[13px] font-sans cursor-pointer hover:border-border-hi transition-colors"
                    >
                        Cancel
                    </button>
                </div>
            </div>
        </div>
    )
}
